### ISSUE TITLE
smoothvideo.json KSampler AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Vektor369** [AInseven/ComfyUI-fastblend#14]
The only thing I changed was the Empty Latent Image size to 512x512.
Any help would be appreciated. Thanks in advance.

**Comment by AInseven** [comment]
Full error message,please. It's very helpful to read if ues Python markdown format, but whatever, full message.

**Comment by Vektor369** [comment]
Sure, thanks. The full error is:

```
22:01:05.047 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
22:01:05.049 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 152, in recursive_execute
22:01:05.050 [Warning] [ComfyUI-0/STDERR]     output_data, output_ui = get_output_data(obj, input_data_all)
22:01:05.051 [Warning] [ComfyUI-0/STDERR]                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.052 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 82, in get_output_data
22:01:05.053 [Warning] [ComfyUI-0/STDERR]     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
22:01:05.054 [Warning] [ComfyUI-0/STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.055 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 75, in map_node_over_list
22:01:05.056 [Warning] [ComfyUI-0/STDERR]     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
22:01:05.057 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.058 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 1373, in sample
22:01:05.059 [Warning] [ComfyUI-0/STDERR]     return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
22:01:05.060 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.061 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 1343, in common_ksampler
22:01:05.062 [Warning] [ComfyUI-0/STDERR]     samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
22:01:05.063 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.063 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
22:01:05.064 [Warning] [ComfyUI-0/STDERR]     return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
22:01:05.065 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.066 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 410, in motion_sample
22:01:05.067 [Warning] [ComfyUI-0/STDERR]     return orig_comfy_sample(model, noise, *args, **kwargs)
22:01:05.068 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.069 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control_reference.py", line 47, in refcn_sample
22:01:05.070 [Warning] [ComfyUI-0/STDERR]     return orig_comfy_sample(model, *args, **kwargs)
22:01:05.071 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.074 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 112, in uncond_multiplier_check_cn_sample
22:01:05.075 [Warning] [ComfyUI-0/STDERR]     return orig_comfy_sample(model, *args, **kwargs)
22:01:05.076 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.077 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\sample.py", line 43, in sample
22:01:05.078 [Warning] [ComfyUI-0/STDERR]     samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
22:01:05.080 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.081 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 829, in sample
22:01:05.082 [Warning] [ComfyUI-0/STDERR]     return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
22:01:05.083 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.084 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 729, in sample
22:01:05.085 [Warning] [ComfyUI-0/STDERR]     return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
22:01:05.086 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.087 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 716, in sample
22:01:05.089 [Warning] [ComfyUI-0/STDERR]     output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
22:01:05.090 [Warning] [ComfyUI-0/STDERR]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.091 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 695, in inner_sample
22:01:05.092 [Warning] [ComfyUI-0/STDERR]     samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
22:01:05.093 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.094 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 600, in sample
22:01:05.095 [Warning] [ComfyUI-0/STDERR]     samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
22:01:05.096 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.097 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
22:01:05.098 [Warning] [ComfyUI-0/STDERR]     return func(*args, **kwargs)
22:01:05.098 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^
22:01:05.099 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\k_diffusion\sampling.py", line 779, in sample_lcm
22:01:05.100 [Warning] [ComfyUI-0/STDERR]     denoised = model(x, sigmas[i] * s_in, **extra_args)
22:01:05.101 [Warning] [ComfyUI-0/STDERR]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.102 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 299, in __call__
22:01:05.103 [Warning] [ComfyUI-0/STDERR]     out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
22:01:05.106 [Warning] [ComfyUI-0/STDERR]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.107 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 682, in __call__
22:01:05.108 [Warning] [ComfyUI-0/STDERR]     return self.predict_noise(*args, **kwargs)
22:01:05.109 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.109 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 685, in predict_noise
22:01:05.110 [Warning] [ComfyUI-0/STDERR]     return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
22:01:05.111 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.112 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 279, in sampling_function
22:01:05.113 [Warning] [ComfyUI-0/STDERR]     out = calc_cond_batch(model, conds, x, timestep, model_options)
22:01:05.114 [Warning] [ComfyUI-0/STDERR]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.115 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 202, in calc_cond_batch
22:01:05.117 [Warning] [ComfyUI-0/STDERR]     c['control'] = control.get_control(input_x, timestep_, c, len(cond_or_uncond))
22:01:05.118 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.119 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 740, in get_control_inject
22:01:05.121 [Warning] [ComfyUI-0/STDERR]     return self.get_control_advanced(x_noisy, t, cond, batched_number)
22:01:05.122 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.124 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 34, in get_control_advanced
22:01:05.125 [Warning] [ComfyUI-0/STDERR]     return self.sliding_get_control(x_noisy, t, cond, batched_number)
22:01:05.125 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.126 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 39, in sliding_get_control
22:01:05.127 [Warning] [ComfyUI-0/STDERR]     control_prev = self.previous_controlnet.get_control(x_noisy, t, cond, batched_number)
22:01:05.128 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.130 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 740, in get_control_inject
22:01:05.131 [Warning] [ComfyUI-0/STDERR]     return self.get_control_advanced(x_noisy, t, cond, batched_number)
22:01:05.132 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.132 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 34, in get_control_advanced
22:01:05.133 [Warning] [ComfyUI-0/STDERR]     return self.sliding_get_control(x_noisy, t, cond, batched_number)
22:01:05.134 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.135 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 90, in sliding_get_control
22:01:05.137 [Warning] [ComfyUI-0/STDERR]     control = self.control_model(x=x_noisy.to(dtype), hint=self.cond_hint, timesteps=timestep.float(), context=context.to(dtype), y=y)
22:01:05.138 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.139 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
22:01:05.140 [Warning] [ComfyUI-0/STDERR]     return self._call_impl(*args, **kwargs)
22:01:05.142 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.143 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
22:01:05.144 [Warning] [ComfyUI-0/STDERR]     return forward_call(*args, **kwargs)
22:01:05.145 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:05.146 [Warning] [ComfyUI-0/STDERR]   File "F:\AI\StableSwarmUI\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\cldm\cldm.py", line 420, in forward
22:01:05.146 [Warning] [ComfyUI-0/STDERR]     assert y.shape[0] == x.shape[0]
22:01:05.147 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^
22:01:05.148 [Warning] [ComfyUI-0/STDERR] AttributeError: 'NoneType' object has no attribute 'shape'
22:01:05.149 [Warning] [ComfyUI-0/STDERR]
```
