### ISSUE TITLE
I want to know how to solve this problem

### ISSUE THREAD

**Issue by xueyuyeye** [AInseven/ComfyUI-fastblend#21]
![44323943-972d-4653-9d85-e0e07dbbe48e](https://github.com/user-attachments/assets/b09bb9bc-84df-42d7-90aa-484b77b2f7c8)
[Diagnostics-1733722828.log](https://github.com/user-attachments/files/18072318/Diagnostics-1733722828.log)
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.5\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\ComfyUI-aki-v1.5\python\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
!!! Exception during processing !!! E:\ComfyUI-aki-v1.5\python\lib\site-packages\cupy\_core\include\cupy\_cuda\cuda-12.4\cuda_fp16.h(129): catastrophic error: cannot open source file "vector_types.h"
  #include "vector_types.h"

**Comment by hillyson** [comment]
same problem

**Comment by Wattson-dog** [comment]
same problem

**Comment by zitounao** [comment]
@hillyson @Wattson-dog try installing the latest CUDA toolkit

**Comment by HT-Sun** [comment]
> [@hillyson](https://github.com/hillyson) [@Wattson-dog](https://github.com/Wattson-dog) try installing the latest CUDA toolkit

upgrade gpu driver and cuda toolkit, reinstall comfyui, solved my problem. 

thank you very much!!!
