### ISSUE TITLE
TypeError: Cannot handle this data type: (1, 1, 576, 3), |u1

### ISSUE THREAD

**Issue by mikeyimer** [AInseven/ComfyUI-fastblend#3]
I got this error at the video-combine item
![图片](https://github.com/AInseven/ComfyUI-fastblend/assets/137673481/e25dea12-bc06-4027-aaa8-999d23942ca4)

**Comment by AInseven** [comment]
It seems that the resolution of the output image sequence is 1x576, and the VHS video combine node can't handle this.
you may check the resolution of empty latent node.

**Comment by aswordok** [comment]
```
Loading 3 new models
100%|████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:23<00:00,  3.87s/it]
!!! Exception during processing!!! Cannot handle this data type: (1, 1, 608, 3), |u1
Traceback (most recent call last):
  File "D:\+AI\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py", line 3089, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
                    ~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: ((1, 1, 608, 3), '|u1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 266, in combine_video
    Image.fromarray(tensor_to_bytes(images[0])).save(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\+AI\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py", line 3092, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 608, 3), |u1

Prompt executed in 50.17 seconds
```
My video is 608x1080, and Empty Latent Image: 608x1080

**Comment by AInseven** [comment]
@aswordok  There is a dubug node that can check the tensor size,you can use it to find where the img size goes to 1,1,n,3

**Comment by aswordok** [comment]
Can you say clear. use this node?:  https://github.com/liusida/ComfyUI-Debug
@AInseven

**Comment by 52Hz-p** [comment]
我发现在Merge image List节点哪怕我连一个图像，都会显示[TypeError：无法处理此数据类型：（1，1，576，3），|u1](https://github.com/AInseven/ComfyUI-fastblend/issues/3#top)，
